#pragma once

#if CONFIG_SOFTWARE_UNIT_ENV2_SUPPORT
#include "sht3x.h"
#include "bmp280.h"
#endif

#if CONFIG_SOFTWARE_UNIT_ENV3_SUPPORT
#include "sht3x.h"
#include "qmp6988.h"
#endif

#if CONFIG_SOFTWARE_UNIT_BME680_SUPPORT
#include "esp32_bme680.h"
#endif

#if CONFIG_SOFTWARE_UNIT_ENV_SCD30_SUPPORT
#include "scd30.h"
#endif

#if CONFIG_SOFTWARE_UNIT_ENV_SCD40_SUPPORT
#include "scd40.h"
#endif

#if CONFIG_SOFTWARE_UNIT_ENV_MHZ19C_SUPPORT
#include "mhz19c.h"
#endif

#if CONFIG_SOFTWARE_UNIT_ADT7410_SUPPORT
#include "adt7410.h"
#endif

#if CONFIG_SOFTWARE_UNIT_BMP280_SUPPORT
#include "bmp280.h"
#endif

#if CONFIG_SOFTWARE_UNIT_QMP6988_SUPPORT
#include "qmp6988.h"
#endif

#if CONFIG_SOFTWARE_UNIT_SK6812_SUPPORT
#include "sk6812.h"
#endif

#if ( CONFIG_SOFTWARE_UNIT_4DIGIT_DISPLAY_SUPPORT || CONFIG_SOFTWARE_UNIT_6DIGIT_DISPLAY_SUPPORT )
#include "tm1637.h"

#ifdef CONFIG_SOFTWARE_UNIT_4DIGIT_DISPLAY_SUPPORT
#define DIGIT_COUNT 4
#elif CONFIG_SOFTWARE_UNIT_6DIGIT_DISPLAY_SUPPORT
#define DIGIT_COUNT 6
#else
#define DIGIT_COUNT 1
#endif

#endif
